### ISSUE TITLE
Expand 3cixty APIs to allow for filtering of places by average rating

### ISSUE THREAD

**Issue by rtroncy** [3cixty/codeless-app-development#4]
_From @AnthonyJameson on September 7, 2016 9:33_
- It should be useful for the codeless apps
- It should be straightforward:
- ?venue schema:aggregateRating ?rating 
- ?rating schema:ratingValue ?ratingValue 
- FILTER(xsd:float(?ratingValue) > 3)
- FILTER(xsd:float(?ratingValue) < 4) 
  See also the separate issue about allowing more than 1 filter to be set in a single endpoint.

_Copied from original issue: AnthonyJameson/codeless-app-development#5_

**Comment by AnthonyJameson** [comment]
I've copied this issue to the knowledgebase-software repository, so I'm closing it here.
