### ISSUE TITLE
Can 3cixty APIs enable multiple filters within a single query?

### ISSUE THREAD

**Issue by rtroncy** [3cixty/codeless-app-development#5]
_From @AnthonyJameson on September 7, 2016 9:50_
- Example: "category = store, keyword = sports"?
- This type of API would be helpful for the codeless apps, since otherwise it is hard or impossible to apply multiple filters

_Copied from original issue: AnthonyJameson/codeless-app-development#6_

**Comment by AnthonyJameson** [comment]
I've copied this issue to the knowledgebase-software repository, so I'm closing it here.
