### ISSUE TITLE
Expand 3cixty APIs to enable global keyword search

### ISSUE THREAD

**Issue by rtroncy** [3cixty/codeless-app-development#9]
_From @AnthonyJameson on September 7, 2016 9:23_
- At least the codeless apps should be able to do keyword search for filtering, which should be a useful building block in many apps.
- It should be quite simple, as indicated by this part of a query from the PE app:
- ?venue rdfs:label ?title . #PRIORITY = 1000
- ?title bif:contains '"sport"' . #PRIORITY = 2000
- Note that only exact matches are considered, not substring matches

_Copied from original issue: AnthonyJameson/codeless-app-development#4_

**Comment by AnthonyJameson** [comment]
I've copied this issue to the knowledgebase-software repository, so I'm closing it here.
